bind 0.0.0.0
protected-mode no
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300
daemonize no
loglevel notice
databases 16
maxmemory-policy allkeys-lru
appendonly yes
appendfilename "appendonly.aof"
